services:
  frontend:
    build:
      context: ./chat-frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./chat-frontend
          target: /app
          ignore:
            - node_modules/
            - npm-debug.log
            - dist/
            - .next/
            - out/

  backend:
    build:
      context: ./chat-backend
      args:
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
        ASPNETCORE_URLS: ${ASPNETCORE_URLS:-http://+:4000}
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS:-http://+:4000}
    develop:
      watch:
        - action: rebuild
          path: ./chat-backend
          target: /app
          ignore:
            - bin/
            - obj/

  # db:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     SA_PASSWORD: 'Your_password123'
  #     ACCEPT_EULA: 'Y'
  #   ports:
  #     - '1433:1433'
  #   healthcheck:
  #     test:
  #       [
  #         'CMD',
  #         'sqlcmd',
  #         '-U',
  #         'sa',
  #         '-P',
  #         'Your_password123',
  #         '-Q',
  #         'select 1',
  #       ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
